import * as Sentry from '@sentry/react-native'

// Initialize Sentry as early as possible in the app lifecycle.
// DSN and other options are read from the native Sentry configuration
// generated by the `@sentry/react-native/expo` plugin, so we don't
// need to pass them explicitly here.
Sentry.init({
  enableAutoPerformanceTracing: true,
})

export default Sentry
